
/*======================================================================*/
/*																		*/
/*								EXTERN.H								*/
/*																		*/
/*======================================================================*/

//#ifndef EXTERN_H
//#define EXTERN_H

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <math.h>
#include <wchar.h>
#include <limits.h>
#include <locale.h>
#include <float.h>

// SDK
#include "DRIVER.H"
#include "BEEPLIB.H"
#include "BITEL_TL.H"
#include "COMMLIB.H"
#include "DES_ECB.H"
#include "FRMWRI.H"
#include "HDLC.H"
#include "HDLCFCS.H"
#include "HSMODEM.H"
#include "KEYDEF.H"
#include "KEYLIB.H"
#include "LCDLIB.H"
#include "MSRLIB.H"
#include "PRINTF.H"
#include "RTCLIB.H"
#include "SYSINFO.H"
#include "TIMERLIB.H"
#include "SYSTEST.H"
#include "country.h"
#include "print.h"
#include "rtc.h"
#include "ictest.h"
#include "app8583.h"
#include "iso8583.h"
#include "modem.h"


#include "jsmn.h"
//#include "cJSON.h"

#include "EBSAPI.H"
#include "e15-ebs.h"
#include "e15api.h"
#include "crypto.h"


#include "http.h"
#include "hmac-sha256.h"
#include "sha1.h"
#include "header.h"
#include "chunk.h"
#include "header.h"


#include "stsdef.h"
#include "main.h"
#include "lcdfontc.h"
#include "prtfontc.h"
#include "lcdlogo.h"
#include "prtlogo.h"
#include "flash.h"
#include "key.h"
#include "keyutil.h"
#include "lcdmsg.h"
#include "lcdmsg1.h"
#include "lcdmsg4.h"
#include "lcdtest.h"
#include "keytest.h"
#include "msrtest.h"
#include "test8583.h"

#include "utf8_2_iso_8859_6.h"


//#endif

/* */

