
/*======================================================================*/
/*																		*/
/*								LCDMSG.H									*/
/*																		*/
/*======================================================================*/

extern const char msg_tbl1[][32];
extern const short msg_tbl4[][4];
extern const char msg_en_tbl1[][32];
/* Display 4 line message on LCD */
extern void StrDisplay(short MsgNo,int L);

/* */
