
#define MSS_INITIAL						0x0000		/* Initial Status */

#define MSS_MAIN_MENU			    	    0xF000		/* Main Menu */
#define MSS_LOGIN					    	0xF100		/* LOG IN */
#define MSS_EMPTY11						0xF110		/* PHONE NO */
#define MSS_EMPTY12					    0xF120		/*  */
#define MSS_EMPTY13					    0xF130		/*  */
#define MSS_EMPTY14						0xF140		/*  */
#define MSS_EMPTY15						0xF150		/*  */
#define MSS_EMPTY16						0xF160		/*  */
#define MSS_EMPTY17						0xF170		/*  */
#define MSS_EMPTY18						0xF180		/*  */
#define MSS_EMPTY19						0xF190	

#define MSS_SETTING_PASSWORD			    0xF200		/* SETTING PASSWORD*/
#define MSS_EMPTY21						0xF210
#define MSS_EMPTY22						0xF220
#define MSS_EMPTY23						0xF230
#define MSS_EMPTY24						0xF240
#define MSS_EMPTY25						    0xF250
#define MSS_EMPTY26					        0xF260
#define MSS_EMPTY27						    0xF270
#define MSS_EMPTY28						    0xF280
#define MSS_EMPTY29						    0xF290

#define MSS_LANGAUGE						0xF300		    /* LANGUAGE */
#define MSS_EMPTY31							0xF310
#define MSS_EMPTY32							0xF320
#define MSS_EMPTY33							0xF330
#define MSS_EMPTY34							0xF340
#define MSS_EMPTY35							0xF350
#define MSS_EMPTY36					    	0xF360
#define MSS_EMPTY37							0xF370
#define MSS_EMPTY38							0xF380
#define MSS_EMPTY39							0xF390

#define MSS_GET_KEY							0xF400			/*   GET KEY   */
#define MSS_EMPTY41							0xF410
#define MSS_EMPTY42							0xF420
#define MSS_EMPTY43							0xF430
#define MSS_EMPTY44							0xF440
#define MSS_EMPTY45							0xF450
#define MSS_EMPTY46					    	0xF460
#define MSS_EMPTY47							0xF470
#define MSS_EMPTY48							0xF480
#define MSS_EMPTY49							0xF490

#define MSS_ORECEIPT						0xF500		/*  MAIN  BILLBAYMANT*/
#define MSS_EMPTY51							0xF510
#define MSS_EMPTY52							0xF520
#define MSS_EMPTY53							0xF530
#define MSS_EMPTY54							0xF540
#define MSS_EMPTY55							0xF550
#define MSS_EMPTY56					    	0xF560
#define MSS_EMPTY57							0xF570
#define MSS_EMPTY58							0xF580
#define MSS_EMPTY59							0xF590

#define MSS_SETTING_MAIN					0xF600		/*SETTING MAIN  */
#define MSS_OINVOIC1						0xF610
#define MSS_E150002							0xF620
#define MSS_E150003							0xF630
#define MSS_E150004							0xF640
#define MSS_E150005							0xF650
#define MSS_E150006							0xF660
#define MSS_E150007							0xF670
#define MSS_E150008							0xF680
#define MSS_E150009							0xF690

#define MSS_EPAYMENT						0xF700		/*  */
#define MSS_EMPTY71							0xF710
#define MSS_EMPTY72							0xF720
#define MSS_EMPTY73							0xF730
#define MSS_EMPTY74							0xF740
#define MSS_EMPTY75							0xF750
#define MSS_EMPTY76					    	0xF760
#define MSS_EMPTY77							0xF770
#define MSS_EMPTY78							0xF780
#define MSS_EMPTY79							0xF790

#define MSS_FRECEIPT						0xF800		/*  */
#define MSS_EMPTY81							0xF810
#define MSS_EMPTY82							0xF820
#define MSS_EMPTY83							0xF830
#define MSS_EMPTY84							0xF840
#define MSS_EMPTY85							0xF850
#define MSS_EMPTY86					    	0xF860
#define MSS_EMPTY87							0xF870
#define MSS_EMPTY88							0xF880
#define MSS_EMPTY89							0xF890

#define MSS_GET_KEY1							0xF900		/*  */
#define MSS_EMPTY91							0xF910
#define MSS_EMPTY92							0xF920
#define MSS_EMPTY93							0xF930
#define MSS_EMPTY94							0xF940
#define MSS_EMPTY95							0xF950
#define MSS_EMPTY96					    	0xF960
#define MSS_EMPTY97							0xF970
#define MSS_EMPTY98							0xF980
#define MSS_EMPTY99							0xF990

#define MSS_CHANGE_PIN							0xFA00		/*  */
#define MSS_EMPTYA1							0xFA10
#define MSS_EMPTYA2							0xFA20
#define MSS_EMPTYA3							0xFA30
#define MSS_EMPTYA4							0xFA40
#define MSS_EMPTYA5							0xFA50
#define MSS_EMPTYA6					  		0xFA60
#define MSS_EMPTYA7							0xFA70
#define MSS_EMPTYA8							0xFA80
#define MSS_EMPTYA9							0xFA90

#define MSS_LANGAUGE1							0xFB00		/*  */
#define MSS_EMPTYB1							0xFB10
#define MSS_EMPTYB2							0xFB20
#define MSS_EMPTYB3							0xFB30
#define MSS_EMPTYB4							0xFB40
#define MSS_EMPTYB5							0xFB50
#define MSS_EMPTYB6					    	0xFB60
#define MSS_EMPTYB7							0xFB70
#define MSS_EMPTYB8							0xFB80
#define MSS_EMPTYB9							0xFB90

#define MSS_SETTING1							0xFC00     /*  */
#define MSS_EMPTYC1							0xFC10 
#define MSS_EMPTYC2							0xFC20
#define MSS_EMPTYC3							0xFC30
#define MSS_EMPTYC4							0xFC40
#define MSS_EMPTYC5							0xFC50
#define MSS_EMPTYC6					    	0xFC60
#define MSS_EMPTYC7							0xFC70
#define MSS_EMPTYC8							0xFC80
#define MSS_EMPTYC9							0xFC90

#define MSS_PLOGIN							0xFD00     /*  */
#define MSS_EMPTYD1							0xFD10
#define MSS_EMPTYD2							0xFD20
#define MSS_EMPTYD3							0xFD30
#define MSS_EMPTYD4							0xFD40
#define MSS_EMPTYD5							0xFD50
#define MSS_EMPTYD6					    	0xFD60
#define MSS_EMPTYD7							0xFD70
#define MSS_EMPTYD8							0xFD80
#define MSS_EMPTYD9							0xFD90

#define MSS_ERROR							0xFE00		/* Error Display  */

#define MSS_KLOGIN							0xFF00     /*  */
#define MSS_EMPTYF1							0xFF10
#define MSS_EMPTYF2							0xFF20
#define MSS_EMPTYF3							0xFF30
#define MSS_EMPTYF4							0xFF40
#define MSS_EMPTYF5							0xFF50
#define MSS_EMPTYF6					    	0xFF60
#define MSS_EMPTYF7							0xFF70
#define MSS_EMPTYF8							0xFF80
#define MSS_EMPTYF9							0xFF90
//#define MSS_JLOGIN							0x1000

#define MSS_TEST11   						0xE000
#define MSS_TEST12              			0xE001
#define MSS_TEST13   						0xE002
#define MSS_TEST14      					0xE003
#define MSS_TEST15  						0xE004


typedef enum
{
	MST_INITIAL = 0,								/* Initial Status */
	
    MST_MAIN_MENU	,		    	    //0xF000		/* Main Menu */
  MST_LOGIN,					    	//0xF100		/* LOG IN */
  MST_EMPTY11,						//0xF110		/*  */
  MST_EMPTY12,					    //0xF120		/*  */
  MST_EMPTY13,					    //0xF130		/*  */
  MST_EMPTY14,						//0xF140		/*  */
  MST_EMPTY15,						//0xF150		/*  */
  MST_EMPTY16,						//0xF160		/*  */
  MST_EMPTY17,						//0xF170		/*  */
  MST_EMPTY18,						//0xF180		/*  */
  MST_EMPTY19,						//0xF190	

  MST_SETTING_PASSWORD,			    //0xF200		/*  */
  MST_EMPTY21,						//0xF210
  MST_EMPTY22,						//0xF220
  MST_EMPTY23,						//0xF230
  MST_EMPTY24,						//0xF240
  MST_EMPTY25,						    //0xF250
  MST_EMPTY26,					        //0xF260
  MST_EMPTY27,						    //0xF270
  MST_EMPTY28,						    //0xF280
  MST_EMPTY29,						    //0xF290

  MST_LANGAUGE,						//0xF300		    /*  */
  MST_EMPTY31,							//0xF310
  MST_EMPTY32,							//0xF320
  MST_EMPTY33,							//0xF330
  MST_EMPTY34,							//0xF340
  MST_EMPTY35,							//0xF350
  MST_EMPTY36,					    	//0xF360
  MST_EMPTY37,							//0xF370
  MST_EMPTY38,							//0xF380
  MST_EMPTY39,							//0xF390

  MST_GET_KEY,							//0xF400
  MST_EMPTY41,							//0xF410
  MST_EMPTY42,							//0xF420
  MST_EMPTY43,							//0xF430
  MST_EMPTY44,							//0xF440
  MST_EMPTY45,							//0xF450
  MST_EMPTY46,					    	//0xF460
  MST_EMPTY47,							//0xF470
  MST_EMPTY48,							//0xF480
  MST_EMPTY49,							//0xF490

  MST_ORECEIPT,						//0xF500		/*  */
  MST_EMPTY51,							//0xF510
  MST_EMPTY52,							//0xF520
  MST_EMPTY53,							//0xF530
  MST_EMPTY54,							//0xF540
  MST_EMPTY55,							//0xF550
  MST_EMPTY56,					    	//0xF560
  MST_EMPTY57,							//0xF570
  MST_EMPTY58,							//0xF580
  MST_EMPTY59,							//0xF590

  MST_SETTING_MAIN,						//0xF600		/*  */
  MST_OINVOIC1,						//0xF610
  MST_E150002,							//0xF620
  MST_E150003,							//0xF630
  MST_E150004,							//0xF640
  MST_E150005,							//0xF650
  MST_E150006,							//0xF660
  MST_E150007,							//0xF670
  MST_E150008,							//0xF680
  MST_E150009,							//0xF690

  MST_EPAYMENT,						//0xF700		/*  */
  MST_EMPTY71,							//0xF710
  MST_EMPTY72,							//0xF720
  MST_EMPTY73,							//0xF730
  MST_EMPTY74,							//0xF740
  MST_EMPTY75,							//0xF750
  MST_EMPTY76,					    	//0xF760
  MST_EMPTY77,							//0xF770
  MST_EMPTY78,							//0xF780
  MST_EMPTY79,							//0xF790

  MST_FRECEIPT,						//0xF800		/*  */
  MST_EMPTY81,							//0xF810
  MST_EMPTY82,							//0xF820
  MST_EMPTY83,							//0xF830
  MST_EMPTY84,							//0xF840
  MST_EMPTY85,							//0xF850
  MST_EMPTY86,					    	//0xF860
  MST_EMPTY87,							//0xF870
  MST_EMPTY88,							//0xF880
  MST_EMPTY89,							//0xF890

  MST_GET_KEY1,							//0xF900		/*  */
  MST_EMPTY91,							//0xF910
  MST_EMPTY92,							//0xF920
  MST_EMPTY93,							//0xF930
  MST_EMPTY94,							//0xF940
  MST_EMPTY95,							//0xF950
  MST_EMPTY96,					    	//0xF960
  MST_EMPTY97,							//0xF970
  MST_EMPTY98,							//0xF980
  MST_EMPTY99,							//0xF990

  MST_CHANGE_PIN,							//0xFA00		/*  */
  MST_EMPTYA1,							//0xFA10
  MST_EMPTYA2,							//0xFA20
  MST_EMPTYA3,							//0xFA30
  MST_EMPTYA4,							//0xFA40
  MST_EMPTYA5,							//0xFA50
  MST_EMPTYA6,					  		//0xFA60
  MST_EMPTYA7,							//0xFA70
  MST_EMPTYA8,							//0xFA80
  MST_EMPTYA9,							//0xFA90

  MST_LANGAUGE1,							//0xFB00		/*  */
  MST_EMPTYB1,							//0xFB10
  MST_EMPTYB2,							//0xFB20
  MST_EMPTYB3,							//0xFB30
  MST_EMPTYB4,							//0xFB40
  MST_EMPTYB5,							//0xFB50
  MST_EMPTYB6,					    	//0xFB60
  MST_EMPTYB7,							//0xFB70
  MST_EMPTYB8,							//0xFB80
  MST_EMPTYB9,							//0xFB90

  MST_SETTING1,							//0xFC00     /*  */
  MST_EMPTYC1,							//0xFC10 
  MST_EMPTYC2,							//0xFC20
  MST_EMPTYC3,							//0xFC30
  MST_EMPTYC4,							//0xFC40
  MST_EMPTYC5,							//0xFC50
  MST_EMPTYC6,					    	//0xFC60
  MST_EMPTYC7,							//0xFC70
  MST_EMPTYC8,							//0xFC80
  MST_EMPTYC9,							//0xFC90

  MST_PLOGIN,							//0xFD00     /*  */
  MST_EMPTYD1,							//0xFD10
  MST_EMPTYD2,							//0xFD20
  MST_EMPTYD3,							//0xFD30
  MST_EMPTYD4,							//0xFD40
  MST_EMPTYD5,							//0xFD50
  MST_EMPTYD6,					    	//0xFD60
  MST_EMPTYD7,							//0xFD70
  MST_EMPTYD8,							//0xFD80
  MST_EMPTYD9,							//0xFD90
  

  MST_KLOGIN,							//0xFF00     /*  */
  MST_EMPTYF1,							//0xFF10
  MST_EMPTYF2,							//0xFF20
  MST_EMPTYF3,							//0xFF30
  MST_EMPTYF4,							//0xFF40
  MST_EMPTYF5,							//0xFF50
  MST_EMPTYF6,					    	//0xFF60
  MST_EMPTYF7,							//0xFF70
  MST_EMPTYF8,							//0xFF80
  MST_EMPTYF9,							//0xFF90
//  MST_JLOGIN							//0x1000

  MST_TEST11,   						//0xE000
  MST_TEST12,              			//0xE001
  MST_TEST13,   						//0xE002
  MST_TEST14,      					//0xE003
  MST_TEST15,  						//0xE004
  MST_ERROR,							//0xFE00
} _eMainService;

/* */
