
/*======================================================================*/
/*																		*/
/*									TEST8583.H							*/
/*																		*/
/*======================================================================*/

extern void Test_iso8583(void);

extern void Test_chr2hex(void);
extern void Test_hex2chr(void);
extern void Test_zchr2hex(void);
extern void Test_hex2zchr(void);

extern void Test_asc2bcd(void);
extern void Test_bcd2asc(void);
extern void Test_zasc2bcd(void);
extern void Test_bcd2zasc(void);

extern void Test_int2LL(void);
extern void Test_int2LLL(void);
extern void Test_LL2int(void);
extern void Test_LLL2int(void);

extern void Test_num_to_num(void);
extern void Test_asc_to_num(void);
extern void Test_num_to_asc(void);
extern void Test_str_to_num(void);
extern void Test_num_to_str(void);

extern void Test_nL2_to_nL2(void);
extern void Test_nL3_to_nL3(void);
extern void Test_str_to_nL2(void);
extern void Test_nL2_to_str(void);

extern void Test_xnu_to_xnu(void);
extern void Test_asc_to_xnu(void);
extern void Test_xnu_to_asc(void);
extern void Test_str_to_xnu(void);
extern void Test_xnu_to_str(void);

extern void Test_str_to_zL2(void);
extern void Test_zL2_to_str(void);
extern void Test_str_to_zL3(void);
extern void Test_zL3_to_str(void);

extern void Test_asc_to_asc(void);
extern void Test_str_to_asc(void);
extern void Test_asc_to_str(void);

extern void Test_aL2_to_aL2(void);
extern void Test_str_to_aL2(void);
extern void Test_aL2_to_str(void);
extern void Test_aL3_to_aL3(void);
extern void Test_str_to_aL3(void);
extern void Test_aL3_to_str(void);

extern void Test_bin_to_bin(void);
extern void Test_hst_to_bin(void);
extern void Test_bin_to_hst(void);

extern void Test_bL2_to_bL2(void);
extern void Test_hst_to_bL2(void);
extern void Test_bL2_to_hst(void);
extern void Test_bL3_to_bL3(void);
extern void Test_hst_to_bL3(void);
extern void Test_bL3_to_hst(void);

/* */
